from typing import Protocol
from datetime import datetime
from agentos.ports.calendar import Event
from agentos.ports.email import EmailThread


class StoragePort(Protocol):

    # ----- EMAIL STORAGE -----
    def save_threads(self, threads: list[EmailThread]) -> None: ...
    def get_recent_threads(self, limit: int) -> list[EmailThread]: ...
    def get_thread(self, thread_id: str) -> EmailThread | None: ...
    def delete_thread(self, thread_id: str) -> None: ...

    # ----- EVENT STORAGE -----
    def save_events(self, events: list[Event]) -> None: ...
    def get_events_between(self, start: datetime, end: datetime) -> list[Event]: ...
    def get_event(self, event_id: str) -> Event | None: ...
    def delete_event(self, event_id: str) -> None: ...

    # ----- SYNC CURSORS -----
    def get_cursor(self, provider: str) -> str | None: ...
    def save_cursor(self, provider: str, cursor: str) -> None: ...
